create table "public"."local-test" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."local-test" enable row level security;

CREATE UNIQUE INDEX "local-test_pkey" ON public."local-test" USING btree (id);

alter table "public"."local-test" add constraint "local-test_pkey" PRIMARY KEY using index "local-test_pkey";

grant delete on table "public"."local-test" to "anon";

grant insert on table "public"."local-test" to "anon";

grant references on table "public"."local-test" to "anon";

grant select on table "public"."local-test" to "anon";

grant trigger on table "public"."local-test" to "anon";

grant truncate on table "public"."local-test" to "anon";

grant update on table "public"."local-test" to "anon";

grant delete on table "public"."local-test" to "authenticated";

grant insert on table "public"."local-test" to "authenticated";

grant references on table "public"."local-test" to "authenticated";

grant select on table "public"."local-test" to "authenticated";

grant trigger on table "public"."local-test" to "authenticated";

grant truncate on table "public"."local-test" to "authenticated";

grant update on table "public"."local-test" to "authenticated";

grant delete on table "public"."local-test" to "service_role";

grant insert on table "public"."local-test" to "service_role";

grant references on table "public"."local-test" to "service_role";

grant select on table "public"."local-test" to "service_role";

grant trigger on table "public"."local-test" to "service_role";

grant truncate on table "public"."local-test" to "service_role";

grant update on table "public"."local-test" to "service_role";